apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: devops-api-ms
spec:  
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-api-ms
    spec:
      containers:
      - name: devops-api-ms
        image: palebluedotstardust.azurecr.io/devops-api-ms:latest
        ports:
         - containerPort: 8889
      imagePullSecrets:
         - name: demo-secret