apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-ms
spec:  
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-ms
    spec:
      containers:
      - name: gateway-ms
        image: palebluedotstardust.azurecr.io/gateway-ms:70
        ports:
         - containerPort: 8888
      imagePullSecrets:
         - name: demo-secret