# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- devopsapi

pool:
  vmImage: 'ubuntu-latest'


variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
  imageRepository: '{{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}'
  containerRegistry: '{{ containerRegistryConnection.Authorization.Parameters.loginServer }}'
  dockerfilePath: '{{ dockerfilePath }}'
  tag: '$(Build.BuildId)'
  azureSubscription: 'demo2 - Service Endpoint'
  resourceGroupName: 'DefaultResourceGroup-EUS'
  kubernetesCluster: 'demo2'

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial (fec8b339-4ad8-4313-9ce8-101211303a36)'
    command: delete deployment devops-api-ms
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'